sonar.projectKey=hms-backend
sonar.projectName=hms-backend
Node App sonar.projectVersion=1.0
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8
# Exclusions
sonar.exclusions=node_modules/**,test/**
# Test coverage
# sonar.tests=test sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Server & auth
sonar.host.url=http://localhost:9000
sonar.login=sqp_e3420e0f1cd8a5d9d1b6c37e074c9e05151050d1



 
 