const PERMISSIONS = Object.freeze({

  READ_PATIENT: "PATIENT:READ",
  CREATE_PATIENT: "PATIENT:CREATE",
  UPDATE_PATIENT: "PATIENT:UPDATE",
  DELETE_PATIENT: "PATIENT:DELETE",


 READ_APPROVALS : "APPROVALS:READ",
 CREATE_APPROVALS : "APPROVALS:CREATE",
 UPDATE_APPROVALS : "APPROVALS:UPDATE",
 DELETE_APPROVALS : "APPROVALS:DELETE",


  READ_DOCTOR: "DOCTOR:READ",
  CREATE_DOCTOR: "DOCTOR:CREATE",
  UPDATE_DOCTOR: "DOCTOR:UPDATE",
  DELETE_DOCTOR: "DOCTOR:DELETE",


  READ_APPOINTMENT: "APPOINTMENT:READ",
  CREATE_APPOINTMENT: "APPOINTMENT:CREATE",
  UPDATE_APPOINTMENT: "APPOINTMENT:UPDATE",
  DELETE_APPOINTMENT: "APPOINTMENT:DELETE",


  READ_EMPLOYEE: "EMPLOYEE:READ",
  CREATE_EMPLOYEE: "EMPLOYEE:CREATE",
  UPDATE_EMPLOYEE: "EMPLOYEE:UPDATE",
  DELETE_EMPLOYEE: "EMPLOYEE:DELETE",


  READ_DEPARTMENT : "DEPARTMENT:READ",
  CREATE_DEPARTMENT : "DEPARTMENT:CREATE",
  UPDATE_DEPARTMENT : "DEPARTMENT:UPDATE",
  DELETE_DEPARTMENT : "DEPARTMENT:DELETE",

});

module.exports = PERMISSIONS;