const PERMISSIONS = Object.freeze({
  // PATIENT
  READ_PATIENT: "PATIENT:READ",
  CREATE_PATIENT: "PATIENT:CREATE",
  UPDATE_PATIENT: "PATIENT:UPDATE",
  DELETE_PATIENT: "PATIENT:DELETE",

  // DOCTOR
  READ_DOCTOR: "DOCTOR:READ",
  CREATE_DOCTOR: "DOCTOR:CREATE",
  UPDATE_DOCTOR: "DOCTOR:UPDATE",
  DELETE_DOCTOR: "DOCTOR:DELETE",

  // APPOINTMENT
  READ_APPOINTMENT: "APPOINTMENT:READ",
  CREATE_APPOINTMENT: "APPOINTMENT:CREATE",
  UPDATE_APPOINTMENT: "APPOINTMENT:UPDATE",
  DELETE_APPOINTMENT: "APPOINTMENT:DELETE",

  // EMPLOYEE
  READ_EMPLOYEE: "EMPLOYEE:READ",
  CREATE_EMPLOYEE: "EMPLOYEE:CREATE",
  UPDATE_EMPLOYEE: "EMPLOYEE:UPDATE",
  DELETE_EMPLOYEE: "EMPLOYEE:DELETE",
});

module.exports = PERMISSIONS;