const ROLES = require('../constants/role.constant');
const PERMISSIONS = require('./permissions');

const ROLE_PERMISSIONS = Object.freeze({

  [ROLES.OWNER]: Object.values(PERMISSIONS), // 🔥 full access

  [ROLES.ADMIN]: [
    PERMISSIONS.READ_PATIENT,
    PERMISSIONS.CREATE_PATIENT,
    PERMISSIONS.UPDATE_PATIENT,

    PERMISSIONS.READ_DOCTOR,
    PERMISSIONS.CREATE_DOCTOR,
    PERMISSIONS.UPDATE_DOCTOR,

    PERMISSIONS.READ_EMPLOYEE,
    PERMISSIONS.CREATE_EMPLOYEE
  ],

  [ROLES.DOCTOR]: [
    PERMISSIONS.READ_PATIENT,
    PERMISSIONS.UPDATE_PATIENT,
    PERMISSIONS.READ_APPOINTMENT
  ],

  [ROLES.RECEPTIONIST]: [
    PERMISSIONS.CREATE_PATIENT,
    PERMISSIONS.READ_PATIENT,
    PERMISSIONS.CREATE_APPOINTMENT,
    PERMISSIONS.READ_APPOINTMENT
  ],

  [ROLES.CASHIER]: [
    PERMISSIONS.READ_PATIENT
  ],

  [ROLES.NURSE]: [
    PERMISSIONS.READ_PATIENT
  ],

  [ROLES.LABTECH]: [
    PERMISSIONS.READ_PATIENT
  ],

  [ROLES.PHARMACIST]: [
    PERMISSIONS.READ_PATIENT
  ],

  [ROLES.PATIENT]: [
    PERMISSIONS.READ_PATIENT
  ]

});

module.exports = ROLE_PERMISSIONS;