const ROLES = require('../constants/role.constant');
const PERMISSIONS = require('./permissions');

const ROLE_PERMISSIONS = Object.freeze({

  [ROLES.OWNER.roleName]: Object.values(PERMISSIONS),

  [ROLES.ADMIN.roleName]: [
    PERMISSIONS.READ_PATIENT,
    PERMISSIONS.CREATE_PATIENT,
    PERMISSIONS.UPDATE_PATIENT,

    PERMISSIONS.READ_DOCTOR,
    PERMISSIONS.CREATE_DOCTOR,
    PERMISSIONS.UPDATE_DOCTOR,

    PERMISSIONS.READ_EMPLOYEE,
    PERMISSIONS.CREATE_EMPLOYEE,
    PERMISSIONS.UPDATE_EMPLOYEE,

    PERMISSIONS.READ_APPOINTMENT,
    PERMISSIONS.CREATE_APPOINTMENT,
    PERMISSIONS.UPDATE_APPOINTMENT,

    PERMISSIONS.CREATE_DEPARTMENT,
    PERMISSIONS.READ_DEPARTMENT,
    
    PERMISSIONS.READ_APPROVALS,
    PERMISSIONS.UPDATE_APPROVALS,
  ],

  [ROLES.DOCTOR.roleName]: [
    PERMISSIONS.READ_PATIENT,
    PERMISSIONS.UPDATE_PATIENT,
    PERMISSIONS.READ_APPOINTMENT
  ],

  [ROLES.RECEPTIONIST.roleName]: [
    PERMISSIONS.CREATE_PATIENT,
    PERMISSIONS.READ_PATIENT,
    PERMISSIONS.CREATE_APPOINTMENT,
    PERMISSIONS.READ_APPOINTMENT,
    PERMISSIONS.UPDATE_APPOINTMENT
  ]

});

module.exports = ROLE_PERMISSIONS;