name: Deploy HMS Backend to EC2

on:
  push:
    branches:
      - feature/sprint5/bonny

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy backend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/HMS/POD-2-HMS/HMS-BACKEND
            git fetch origin
            git checkout feature/sprint5/bonny
            git pull origin feature/sprint5/bonny
            npm install
            pm2 restart hms-backend
            pm2 save